services:
  web:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    env:
      - .env
    volumes:
      - .:/app
    networks:
      - app-network
  db:
      image: postgres:16-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      expose:
        - 5432
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      networks:
        - app-network

volumes:
      postgres_data: 
  
networks:
  app-network:
    driver: bridge